# Generated by Django 5.0.2 on 2024-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_developer_developerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerprofile',
            old_name='status',
            new_name='role',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
