# Generated by Django 5.0.2 on 2024-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_developerprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='role',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Software Engineer', 'Software Engineer')], default='Software Developer', max_length=255),
        ),
    ]
