# Generated by Django 5.0.2 on 2024-02-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_timeline",
            new_name="project_type",
        ),
    ]
