# Generated by Django 5.0.2 on 2024-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_project_timeline_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="slug",
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
