# Generated by Django 5.0.2 on 2024-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_project_availability_project_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_availability",
        ),
        migrations.AddField(
            model_name="project",
            name="project_progress",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Active"), ("C", "Completed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[("A", "Available"), ("N", "Not Available")],
                default="A",
                max_length=1,
            ),
        ),
    ]
