# Generated by Django 5.0.2 on 2024-02-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_bid_status_alter_project_project_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['project']},
        ),
    ]
